{
  'Version': '2012-10-17',
  'Statement':
    [
      {
        'Effect': 'Allow',
        'Action': ['s3:PutObject', 's3:DeleteObject', 's3:ListBucket'],
        'Resource': '*',
      },
      {
        'Effect': 'Allow',
        'Action':
          ['cloudfront:CreateInvalidation', 'cloudfront:GetDistribution'],
        'Resource': '*',
      },
    ],
}
